export const COMARCAS = [
  "Alto Gállego",
  "Bajo Cinca",
  "Cinca Medio",
  "Hoya de Huesca",
  "Jacetania",
  "La Litera",
  "Monegros",
  "Ribagorza",
  "Sobrarbe",
  "Somontano de Barbastro",
];

const MUNICIPALITIES: Record<string, string[]> = {
  "Alto Gállego": [
    "sabinanigo",
    "biescas",
    "panticosa",
    "sallent de gallego",
    "escarrilla",
    "formigal",
    "caldearenas",
    "lanuza",
    "tramacastilla",
    "hosca",
  ],
  "Bajo Cinca": ["fraga", "ballobar", "zaidin", "torrente de cinca", "belver de cinca"],
  "Cinca Medio": [
    "monzon",
    "alcolea de cinca",
    "alfantega",
    "binaced",
    "pueyo de santa cruz",
    "san miguel del cinca",
    "velilla de cinca",
  ],
  "Hoya de Huesca": [
    "huesca",
    "ayerbe",
    "quicena",
    "sangarren",
    "tierz",
    "chimillas",
    "banastas",
    "monflorite-lascasas",
    "lescuen",
    "nueno",
    "siétamo",
    "ibieca",
    "angués",
    "la sotonera",
    "loarre",
    "loscorrales",
    "pertusa",
    "piracés",
    "salillas",
    "sesa",
    "novales",
    "loporzano",
    "almudévar",
    "alcubierre",
    "gurrea de gállego",
    "las peñas de riglos",
    "casbas de huesca",
    "blecua y torres",
    "antillon",
    "argavieso",
    "arascues",
  ],
  Jacetania: [
    "jaca",
    "canfranc",
    "villanua",
    "aisa",
    "anso",
    "valle de hecho",
    "aragues del puerto",
    "borau",
    "castiello de jaca",
    "fago",
    "jasa",
    "mianos",
    "puente la reina de jaca",
    "salvatierra de esca",
    "santa cilia",
    "santa cruz de la seros",
    "siguez",
    "urdues",
    "caldearenas",
  ],
  "La Litera": [
    "binefar",
    "tamarite de litera",
    "alcampell",
    "albelda",
    "altorricon",
    "baells",
    "baldellou",
    "camporrells",
    "castillonroy",
    "san esteban de litera",
    "vencillon",
    "esplus",
  ],
  Monegros: [
    "sariñena",
    "lanaja",
    "tardienta",
    "grañén",
    "lalueza",
    "robres",
    "sena",
    "huerto",
    "castelflorite",
    "valfarta",
    "almuniente",
    "barbues",
    "castellon de monegros",
    "peralta de alcofea",
    "poleñino",
    "albalatillo",
    "alberuela de tubo",
    "villanueva de sigena",
  ],
  Ribagorza: [
    "benasque",
    "graus",
    "campo",
    "cerler",
    "aren",
    "bonansa",
    "castejon de sos",
    "chia",
    "valle de bardaji",
    "laspaules",
    "montanuy",
    "sahun",
    "seira",
    "tolva",
    "lascuarre",
    "perarrua",
    "isabena",
    "capella",
    "estopinan del castillo",
    "ventanillo",
    "villanova",
  ],
  Sobrarbe: [
    "ainsa",
    "boltaña",
    "broto",
    "torla",
    "fiscal",
    "fanlo",
    "gistaín",
    "plan",
    "puertolas",
    "tella-sin",
    "bielsa",
    "la fueva",
    "abizanda",
    "mediano",
    "javierre de olson",
    "barbaruens",
    "palo",
  ],
  "Somontano de Barbastro": [
    "barbastro",
    "alquézar",
    "adahuesca",
    "abiego",
    "azara",
    "azlor",
    "barcabo",
    "bierge",
    "colungo",
    "el grado",
    "estada",
    "estadilla",
    "ilche",
    "olvera",
    "naval",
    "olvena",
    "salas altas",
    "salas bajas",
    "pozan de vero",
    "peraltilla",
    "santa maria de dulcis",
    "torres de alcanadre",
  ],
};

function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function restaurantZoneFromAddress(
  address: string | null | undefined
): string | null {
  if (!address) return null;
  const norm = normalize(address);
  for (const comarca of COMARCAS) {
    const keywords = MUNICIPALITIES[comarca] ?? [];
    if (keywords.some((keyword) => norm.includes(keyword))) return comarca;
  }
  return null;
}

export function restaurantsFilteredByZone(
  items: Array<{ address: string | null | undefined }>,
  zone: string | null
): Array<{ address: string | null | undefined }> {
  if (!zone) return items;
  return items.filter((item) => restaurantZoneFromAddress(item.address) === zone);
}